<Project Sdk="Aspire.AppHost.Sdk/13.4.2">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>dfe53287-ac1c-469a-9605-e32984727cf0</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\OG.Gateway.Api\OG.Gateway.Api.csproj" />
        <ProjectReference Include="..\OG.Dashboard.Api\OG.Dashboard.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.3" />
        <PackageReference Include="Aspire.Hosting.Redis"      Version="13.4.3" />
    </ItemGroup>

</Project>
