<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Features\AuditLogs\" />
        <Folder Include="Features\Metrics\" />
        <Folder Include="Features\Policies\" />
        <Folder Include="Features\RiskConfig\" />
        <Folder Include="Features\Roles\" />
        <Folder Include="Features\ServicePolicies\" />
        <Folder Include="Features\Users\" />
    </ItemGroup>

</Project>
