// <auto-generated />
using System;
using System.Text.Json;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(OmakaseDbContext))]
    [Migration("20260715031633_AddMfaFieldsToUsers")]
    partial class AddMfaFieldsToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("type");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("access_policies", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AnomalyScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("anomaly_score");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("evaluated_at");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<string>("FingerprintHash")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("fingerprint_hash");

                    b.Property<JsonDocument>("Geo")
                        .HasColumnType("jsonb")
                        .HasColumnName("geo");

                    b.Property<decimal>("PolicyScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("policy_score");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("risk_score");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("source_ip");

                    b.Property<JsonDocument>("TriggeredRules")
                        .HasColumnType("jsonb")
                        .HasColumnName("triggered_rules");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("verdict");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedAt")
                        .HasDatabaseName("ix_audit_logs_evaluated_at");

                    b.HasIndex("EvaluationId")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_logs_evaluation_id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TriggeredRules")
                        .HasDatabaseName("ix_audit_logs_triggered_rules_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TriggeredRules"), "GIN");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProtectedService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresAuth")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_auth");

                    b.Property<string>("UpstreamUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("upstream_url");

                    b.HasKey("Id");

                    b.ToTable("protected_services", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("device_info");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("ix_refresh_tokens_user_active")
                        .HasFilter("is_revoked = false");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RiskScoreConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AnomalyWeight")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("anomaly_weight");

                    b.Property<decimal>("BlockThreshold")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("block_threshold");

                    b.Property<decimal>("ChallengeThreshold")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("challenge_threshold");

                    b.Property<int>("ColdStartN")
                        .HasColumnType("integer")
                        .HasColumnName("cold_start_n");

                    b.Property<decimal>("ColdStartPenalty")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("cold_start_penalty");

                    b.Property<decimal>("PolicyWeight")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("policy_weight");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("risk_score_config", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ServicePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("ServiceId", "PolicyId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_policies_service_policy");

                    b.ToTable("service_policies", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsInteractive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_interactive");

                    b.Property<string>("KeycloakSub")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("keycloak_sub");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MfaEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("totp_secret");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakSub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_keycloak_sub")
                        .HasFilter("keycloak_sub IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserBehaviorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_count");

                    b.Property<decimal>("BaseRiskPenalty")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("base_risk_penalty");

                    b.Property<JsonDocument>("FeatureVector")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_vector");

                    b.Property<bool>("IsColdStart")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cold_start");

                    b.Property<DateTimeOffset?>("LastTrainedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_trained_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_behavior_profiles_user_id");

                    b.ToTable("user_behavior_profiles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_user_role");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AccessPolicy", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedPolicies")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Domain.Entities.ProtectedService", "ProtectedService")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProtectedService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ServicePolicy", b =>
                {
                    b.HasOne("Domain.Entities.AccessPolicy", "AccessPolicy")
                        .WithMany("ServicePolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProtectedService", "ProtectedService")
                        .WithMany("ServicePolicies")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPolicy");

                    b.Navigation("ProtectedService");
                });

            modelBuilder.Entity("Domain.Entities.UserBehaviorProfile", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("BehaviorProfile")
                        .HasForeignKey("Domain.Entities.UserBehaviorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.AccessPolicy", b =>
                {
                    b.Navigation("ServicePolicies");
                });

            modelBuilder.Entity("Domain.Entities.ProtectedService", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ServicePolicies");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BehaviorProfile");

                    b.Navigation("CreatedPolicies");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
